### ISSUE TITLE
`-Werror -Weverything` may be too fragile

### ISSUE THREAD

**Issue by ISSOtm** [mdagois/gca#4]
We're adding new warnings in minor releases as well, as those are not considered breaking changes. Therefore, `rgbasm -Werror -Weverything` may break in the next release, especially considering that `def`-less symbol definitions should be deprecated soon. (Either v0..6.1 or v0.7.0, though the latter is more likely atm.)

I'd suggest either doing without `-Werror`, or being more selective than `-Weverything`; `-Wall -Wextra` may be indicated. (Take the latter with a grain of salt, as `-Wobsolete` is in the default flag set anyway.)

**Comment by mdagois** [comment]
OK, so the truth is I like when it breaks. :)
I watch releases of RGBDS and I plan on always upgrading to the latest one asap, so that the samples are always following the _best practice_ from RGBDS. It happened recently with the old macro syntax deprecation. I put the version of RGBDS I tested the sample against in the README.
Are there any `rgbasm` warnings that might generate false positives? GCC and clang have quite a lot of those, so `-Weverything` is not usable there. But for `rgbasm`, my intuition was that there were no risk of false positives.

**Comment by ISSOtm** [comment]
The warnings that have several levels can currently present false positives, but they're really fringe.

**Comment by mdagois** [comment]
OK, I think there is a good compromise.
I will keep `-Werror -Weverything` for the samples, but I will add a note in the book mentioning that `-Wall -Wextra`, while not covering as many warnings, is less prone to false positives.

I will also be proactive in checking the toolchain/sample compatibility.

**Comment by ISSOtm** [comment]
Thanks!
